#!/usr/bin/env python3

import math
import re
import socket
import struct
import sys

HOST_PORT = ('224.1.1.1', 5005)
UID = '229049'

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

for line in sys.stdin:
    msg = UID + line
    sock.sendto(msg.encode(), HOST_PORT)
