#!/usr/bin/env python3

import sys
import websocket

URL = 'ws://tcpip.epfl.ch:5006'

cmd, = sys.argv[1:]

def on_message(ws, message):
    print(message.decode())

def on_open(ws):
    ws.send(cmd)

ws = websocket.WebSocketApp(URL,
        on_open=on_open,
        on_message=on_message
    )
ws.run_forever()
